### ISSUE TITLE
Double check your document before commit/submit

### ISSUE THREAD

**Issue by huntertran** [serum-390/soen390-team16-godzilla#104]
when submitting documents in the wiki or in the main source code repo, make sure they are displaying well before you finish the work

![image](https://user-images.githubusercontent.com/4468525/108081028-7f3e3a80-703e-11eb-995b-0b252498dda6.png)

**Comment by instamine** [comment]
Thank you for the heads up!

**Comment by obonobo** [comment]
Hi @huntertran, I'm not able to replicate that issue on my end. Can you send some details about your environment (OS, browser, etc.)?

It looks like github is showing you raw html - the docs are written in markdown (those html tags are not ours), so it's just not rendering the html in your browser for some reason.

**Comment by obonobo** [comment]
For reference, here is an image of what the contributors wiki page should look like: <https://github.com/serum-390/soen390-team16-godzilla/wiki/Contributors>

![image](https://user-images.githubusercontent.com/52555183/108575750-4675be00-72e9-11eb-840c-947d117acd01.png)

**Comment by obonobo** [comment]
Im not sure if this will fix the issue, but I would try:

- Restarting your browser
- Opening the page in a different browser

Something like that, I've tried opening the page a few different ways and I can't seem to get it to display the raw html like in your image

**Comment by instamine** [comment]
Multiple team members have tried opening *Contributors* to escalate this issue. and it displayed as required with no issue.
