### ISSUE TITLE
BUG: about page has infinite loader

### ISSUE THREAD

**Issue by obonobo** [serum-390/soen390-team16-godzilla#127]
**Describe the bug**
There is an infinite progress spinner on the about page of the app. The spinner was inserted in the same PR that the other loading spinners were inserted in.

**To Reproduce**
1. Run the app
2. Navigate to the about page: <https://godzilla.serum-390.app/about>
3. Observe the never-ending spinner

**Expected behavior**
Remove the spinner. Fill the about page with useful info, or remove the about page and add the about information to the navbar drawer like they do on YouTube.

**Environment**
Occurs on all browsers, and operating systems.

**Images**
![image](https://user-images.githubusercontent.com/52555183/109074327-9f689c00-76c5-11eb-9279-1ec6af1bd3b6.png)

**Comment by tashfia98** [comment]
It was corrected.
