### ISSUE TITLE
User story backlog and release plan

### ISSUE THREAD

**Issue by obonobo** [serum-390/soen390-team16-godzilla#131]
## Backlog 

- **SPRINT 2:** <https://docs.google.com/document/d/1bn2r12bgm8PIKLyNm68sr3J-0jNJ0AUX1Vlv5YDhsL4/edit?usp=sharing>
- **SPRINT 3:** <https://docs.google.com/document/d/1aUddqG6EEascno3Yo7ud4ukxMCfkX6rUVel_0fPakI8/edit?usp=sharing>

## Release Plan (Sprints 2 and 3)
<https://drive.google.com/file/d/1EDrJakhFgG2C2uANolJy8cy6X3pRWi-O/view?usp=sharing>

**Comment by JustinLohKingWei** [comment]
User Story for sprint 2 and 3 has been completed and edited in accordance to new features

**Comment by obonobo** [comment]
The user story backlog and release plan are complete. This issue is pinned to provide a convenient link to the docs.
