### ISSUE TITLE
Customer managment

### ISSUE THREAD

**Issue by obonobo** [serum-390/soen390-team16-godzilla#60]
**Is your feature request related to a problem? Please describe.**
I would like to be able to manage customers on Godzilla ERP:
- Adding customers
- Removing customers
- Editing customer settings stored in the ERP

**Describe the solution you'd like**
A view that provides access to various features relevant to Vendors.

## Child Issues

This issue can only be closed when its children have been closed:
- #61 
- #62

**Comment by shushengfuqin** [comment]
query customer table
