### ISSUE TITLE
Fully implemented Accounting view

### ISSUE THREAD

**Issue by JustinLohKingWei** [serum-390/soen390-team16-godzilla#75]
**Is your feature request related to a problem? Please describe.**
I am unable to view the credit/debit information on my financial account balance

**Describe the solution you'd like**
I would like a organised view to view the credit/debit information on my financial account balance

**Comment by instamine** [comment]
Duplicate of #54

**Comment by instamine** [comment]
#54

**Comment by instamine** [comment]
#54
